export default {
  0: {
    id: 0,
    name: 'Вода',
    imageName: 'water',
    fraction: 999,
    level: 1,
  },
  1: {
    id: 1,
    name: 'Огонь',
    imageName: 'fire',
    fraction: 999,
    level: 1,
  },
  2: {
    id: 2,
    name: 'Земля',
    imageName: 'ground',
    fraction: 999,
    level: 1,
  },
  3: {
    id: 3,
    name: 'Уголь',
    imageName: 'coal',
    fraction: 999,
    level: 1,
  },
  4: {
    id: 4,
    name: 'Метал',
    imageName: 'metal',
    fraction: 999,
    level: 1,
  },
  5: {
    id: 5,
    name: 'Песок',
    imageName: 'sand',
    fraction: 999,
    level: 1,
  },
  6: {
    id: 6,
    name: 'Соль',
    imageName: 'salt',
    fraction: 999,
    level: 1,
  },
  7: {
    id: 7,
    name: 'Грибочки',
    imageName: 'shrooms',
    fraction: 999,
    level: 1,
  },
  8: {
    id: 8,
    name: 'Подорожник',
    imageName: 'leaf',
    fraction: 999,
    level: 1,
  },
  9: {
    id: 9,
    name: 'Картошка',
    imageName: 'potato',
    fraction: 0,
    level: 1,
  },
  10: {
    id: 10,
    name: 'Воздух',
    imageName: 'air',
    fraction: 0,
    level: 1,
  },
  11: {
    id: 11,
    name: 'Спирт',
    imageName: 'alcohol',
    fraction: 0,
    level: 1,
  },
  12: {
    id: 12,
    name: 'Глицерин',
    imageName: 'glycerol',
    fraction: 0,
    level: 2,
  },
  13: {
    id: 13,
    name: 'Бытовая пыль',
    imageName: 'dust',
    fraction: 0,
    level: 2,
  },
  14: {
    id: 14,
    name: 'Зарплата',
    imageName: 'salary',
    fraction: 0,
    level: 2,
  },
  15: {
    id: 15,
    name: 'Бензин',
    imageName: 'petrol',
    fraction: 0,
    level: 2,
  },
  16: {
    id: 16,
    name: 'Ткань',
    imageName: 'fabric',
    fraction: 0,
    level: 2,
  },
  17: {
    id: 17,
    name: 'Уран',
    imageName: 'nuke',
    fraction: 0,
    level: 3,
  },
  18: {
    id: 18,
    name: 'Кровь единорога',
    imageName: 'unicorn',
    fraction: 1,
    level: 1,
  },
  19: {
    id: 19,
    name: 'Лист священного дерева',
    imageName: 'holy-leaf',
    fraction: 1,
    level: 1,
  },
  20: {
    id: 20,
    name: 'Лунная призма',
    imageName: 'moon-prism',
    fraction: 1,
    level: 1,
  },
  21: {
    id: 21,
    name: 'Язык дракона',
    imageName: 'dragon',
    fraction: 1,
    level: 2,
  },
  22: {
    id: 22,
    name: 'Колдовская пыль',
    imageName: 'magic-dust',
    fraction: 1,
    level: 2,
  },
  23: {
    id: 23,
    name: 'Лесной дух',
    imageName: 'soul',
    fraction: 1,
    level: 2,
  },
  24: {
    id: 24,
    name: 'Любовная стрела',
    imageName: 'arrow',
    fraction: 1,
    level: 2,
  },
  25: {
    id: 25,
    name: 'Шелк',
    imageName: 'silk',
    fraction: 1,
    level: 2,
  },
  26: {
    id: 26,
    name: 'Глаз предка',
    imageName: 'ancestor',
    fraction: 1,
    level: 3,
  },
  27: {
    id: 27,
    name: 'Собственная кровь',
    imageName: 'blood-own',
    fraction: 2,
    level: 1,
  },
  28: {
    id: 28,
    name: 'Пшеница',
    imageName: 'wheat',
    fraction: 2,
    level: 1,
  },
  29: {
    id: 29,
    name: 'Сопли',
    imageName: 'goo',
    fraction: 2,
    level: 1,
  },
  30: {
    id: 30,
    name: 'Череп бизона',
    imageName: 'skull',
    fraction: 2,
    level: 2,
  },
  31: {
    id: 31,
    name: 'Прах вождя',
    imageName: 'leader',
    fraction: 2,
    level: 2,
  },
  32: {
    id: 32,
    name: 'Боевой клич',
    imageName: 'battlecry',
    fraction: 2,
    level: 2,
  },
  33: {
    id: 33,
    name: 'Порох',
    imageName: 'powder',
    fraction: 2,
    level: 2,
  },
  34: {
    id: 34,
    name: 'Волчья шкура',
    imageName: 'wolf',
    fraction: 2,
    level: 2,
  },
  35: {
    id: 35,
    name: 'Кровь оппонента',
    imageName: 'blood-opponent',
    fraction: 2,
    level: 3,
  },
  36: {
    id: 36,
    name: 'Кусочек метеорита',
    imageName: 'meteorite',
    fraction: 3,
    level: 1,
  },
  37: {
    id: 37,
    name: 'Квантовая частица',
    imageName: 'particle',
    fraction: 3,
    level: 1,
  },
  38: {
    id: 38,
    name: 'Кристаллы',
    imageName: 'crystal',
    fraction: 3,
    level: 1,
  },
  39: {
    id: 39,
    name: 'Энергия звезды',
    imageName: 'star-energy',
    fraction: 3,
    level: 2,
  },
  40: {
    id: 40,
    name: 'Звездная пыль',
    imageName: 'stardust',
    fraction: 3,
    level: 2,
  },
  41: {
    id: 41,
    name: 'Сингулярность',
    imageName: 'singularity',
    fraction: 3,
    level: 2,
  },
  42: {
    id: 42,
    name: 'Спутник',
    imageName: 'satellite',
    fraction: 3,
    level: 2,
  },
  43: {
    id: 43,
    name: 'Темная материя',
    imageName: 'dark-matter',
    fraction: 3,
    level: 2,
  },
  44: {
    id: 44,
    name: 'Манипулятор времени',
    imageName: 'time',
    fraction: 3,
    level: 3,
  },
};
